adding customer controller & validation of current_owner
the-hacking-team/happy-minute pull request #31
Opened 2020-09-09 20:48 UTC by StanislasBASQUIN

2020-09-09 22:40 UTC, mvoland approved these changes

2020-09-10 07:38 UTC, Vivien-Ploix approved these changes

2020-09-10 07:52 UTC, mathieu-superpose approved these changes

2020-09-10 07:52 UTC, mvoland requested changes

2020-09-10 07:52 UTC, mvoland commented on app/views/businesses/show.html.erb
> +  <% if owner_signed_in? && current_owner = business.owner %>
```suggestion
  <% if owner_signed_in? && current_owner = @business.owner %>
```

2020-09-10 07:56 UTC, mvoland approved these changes

2020-09-10 07:58 UTC, merged

2020-09-10 15:11 UTC, StanislasBASQUIN commented
![](https://github.trello.services/images/mini-trello-icon.png) [Conception du Profil Customer](https://trello.com/c/ItKn0Ab9/93-conception-du-profil-customer)