Rescue email sending
the-hacking-team/happy-minute pull request #87
Opened 2020-09-16 23:29 UTC by Laurent-Gi

The 550 error is now corrected
And the  root path for owner is set again to business#index

2020-09-16 23:42 UTC, mathieu-superpose requested changes

2020-09-16 23:42 UTC, mathieu-superpose commented on app/models/owner.rb
> +      puts "="*80
Puts should be removed

2020-09-17 09:58 UTC, Vivien-Ploix approved these changes

2020-09-17 10:01 UTC, Laurent-Gi commented on app/models/owner.rb
> +      puts "="*80
done

2020-09-17 10:01 UTC, StanislasBASQUIN approved these changes

2020-09-17 10:03 UTC, merged